MvcCoreProceduresEF/Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("DOCTOR")]
    public class Doctor
    {
        [Key]
        [Column("HOSPITAL_COD")]
        public int idHospital { get; set; }

        [Column("DOCTOR_NO")]
        public int idDoctor { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("ESPECIALIDAD")]
        public string Especialidad { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

MvcCoreProceduresEF/Models/Enfermo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("ENFERMO")]
    public class Enfermo
    {
        [Key]
        [Column("INSCRIPCION")]
        public int Inscripcion { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("DIRECCION")]
        public string Direccion { get; set; }

        [Column("FECHA_NAC")]
        public DateTime FechaNacimiento { get; set; }

        [Column("S")]
        public string Genero { get; set; }
    }
}

MvcCoreProceduresEF/Models/ErrorViewModel.cs
namespace MvcCoreProceduresEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreProceduresEF/Models/Trabajador.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("V_TRABAJADORES")]
    public class Trabajador
    {
        [Key]
        [Column("IDTRABAJADOR")]
        public int IdTrabajador { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

MvcCoreProceduresEF/Models/TrabajadoresModel.cs
namespace MvcCoreProceduresEF.Models
{
    public class TrabajadoresModel
    {
        public List<Trabajador> Trabajadores { get; set; }
        public int Personas { get; set; }
        public int SumaSalarial { get; set; }
        public int MediaSalarial { get; set;}
    }
    
}

MvcCoreProceduresEF/Models/ViewEmpleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreProceduresEF.Models
{
    [Table("V_EMP_DEPT")]
    public class ViewEmpleado
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("DEPARTAMENTO")]
        public string Departamento { get; set; }

        [Column("LOCALIDAD")]
        public string Localidad { get; set; }
    }
}

MvcCoreProceduresEF/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class DoctoresController : Controller
    {
        private RepositoryDoctores repo;

        public DoctoresController(RepositoryDoctores repo)
        {
            this.repo = repo;
        }

        public IActionResult IncrementarSalarios()
        {
            List<string> especialidades = this.repo.GetEspecialidades();
            ViewData["ESPECIALIDADES"] = especialidades;
            return View();
        }
        [HttpPost]
        public IActionResult IncrementarSalarios
            (string especialidad, int incremento)
        {
            List<string> especialidades = this.repo.GetEspecialidades();
            ViewData["ESPECIALIDADES"] = especialidades;
            List<Doctor> afectados = this.repo.Incrementar(especialidad, incremento);
            return View(afectados);
        }
    }
}

MvcCoreProceduresEF/Controllers/EmpleadosViewController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Repositories;
using MvcCoreProceduresEF.Models;

namespace MvcCoreProceduresEF.Controllers
{
    public class EmpleadosViewController : Controller
    {
        private RepositoryViewEmpleados repo;

        public EmpleadosViewController(RepositoryViewEmpleados repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<ViewEmpleado> model = await this.repo.GetEmpleadosAsync();
            return View(model);
        }
    }
}

MvcCoreProceduresEF/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class EnfermosController : Controller
    {
        private RepositoryEnfermos repo;

        public EnfermosController (RepositoryEnfermos repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult IndexView()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(int inscripcion)
        {
            Enfermo enfermo = this.repo.FindEnfermo(inscripcion);
            return View(enfermo);
        }

        public IActionResult Delete(int inscripcion)
        {
            this.repo.DeleteEnfermo(inscripcion);
            return RedirectToAction("IndexView");
        }

        public IActionResult Insertar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Insertar(Enfermo enfermo)
        {
            this.repo.InsertarEnfermo(enfermo.Inscripcion, enfermo.Apellido,
                enfermo.Direccion, enfermo.FechaNacimiento, enfermo.Genero);
            return RedirectToAction("IndexView");
        }
    }
}

MvcCoreProceduresEF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using System.Diagnostics;

namespace MvcCoreProceduresEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreProceduresEF/Controllers/TrabajadoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreProceduresEF.Models;
using MvcCoreProceduresEF.Repositories;

namespace MvcCoreProceduresEF.Controllers
{
    public class TrabajadoresController : Controller
    {
        private RepositoryTrabajadores repo;

        public TrabajadoresController(RepositoryTrabajadores repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Trabajador> workers =
                await this.repo.GetTrabajadoresAsync();
            return View(workers);
        }

        public async Task<IActionResult> TrabajadoresOficio()
        {
            List<string> oficios = await this.repo.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> TrabajadoresOficio(string oficio)
        {
            List<string> oficios = await this.repo.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;
            TrabajadoresModel model =
                await this.repo.GetTrabajadoresOficioAsync(oficio);
            return View(model);
        }
    }
}

MvcCoreProceduresEF/Views/Doctores/IncrementarSalarios.cshtml
@model List<Doctor>
@{
    List<string> especialidades = (List<string>)ViewData["ESPECIALIDADES"];
}
<h1>Incrementar salarios</h1>

<form method="post">

    <label>Especialidad:</label>
    <select class="form-control" name="especialidad">
        @foreach (string e in especialidades)
        {
            <option>@e</option>
        }
    </select>
    <br />
    <label>Incremento:</label>
    <input type="number" name="incremento" class="form-control" />
    <br />
    <button class="btn btn-success">Incrementar</button>
</form>

@if (Model != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <td>Apellido</td>
                <td>Especialidad</td>
                <td>Salario</td>
            </tr>
        </thead>
        <tbody>
            @foreach (Doctor e in Model)
            {
                <tr>
                    <td>@e.Apellido</td>
                    <td>@e.Especialidad</td>
                    <td>@e.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreProceduresEF/Views/EmpleadosView/Index.cshtml
@model IEnumerable<MvcCoreProceduresEF.Models.ViewEmpleado>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@*@if(Model != null)
{*@
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Oficio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Departamento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Localidad)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Oficio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Departamento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Localidad)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>

MvcCoreProceduresEF/Views/Enfermos/Details.cshtml
@model MvcCoreProceduresEF.Models.Enfermo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Enfermo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inscripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcCoreProceduresEF/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Listado de enfermos</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <td>Apellido</td>
            <td>Direccion</td>
            <td>Fecha de Nacimiento</td>
            <td>Genero</td>
        </tr>
    </thead>
    <tbody>
        @foreach (Enfermo e in Model)
        {
            <tr>
                <td>@e.Apellido</td>
                <td>@e.Direccion</td>
                <td>@e.FechaNacimiento</td>
                <td>@e.Genero</td>
            </tr>
        }
    </tbody>
</table>

MvcCoreProceduresEF/Views/Enfermos/IndexView.cshtml
@model IEnumerable<MvcCoreProceduresEF.Models.Enfermo>

@{
    ViewData["Title"] = "IndexView";
}

<h1>IndexView</h1>

<p>
    <a asp-action="Insertar">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Inscripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Inscripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { inscripcion = item.Inscripcion }) |
                @Html.ActionLink("Delete", "Delete", new { inscripcion = item.Inscripcion })
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreProceduresEF/Views/Enfermos/Insertar.cshtml
@model MvcCoreProceduresEF.Models.Enfermo

@{
    ViewData["Title"] = "Insertar";
}

<h1>Insertar</h1>

<h4>Enfermo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insertar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Inscripcion" class="control-label"></label>
                <input asp-for="Inscripcion" class="form-control" />
                <span asp-validation-for="Inscripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MvcCoreProceduresEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreProceduresEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreProceduresEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreProceduresEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreProceduresEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Enfermos" asp-action="IndexView">Vista generada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Doctores" asp-action="IncrementarSalarios">Incrementar salarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="EmpleadosView" asp-action="Index">Empleados View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Trabajadores" asp-action="Index">Trabajadores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreProceduresEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreProceduresEF/Views/Trabajadores/Index.cshtml
@model IEnumerable<MvcCoreProceduresEF.Models.Trabajador>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a asp-controller="Trabajadores" asp-action="TrabajadoresOficio"
   class="btn btn-success">
    Buscar oficios
</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdTrabajador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oficio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdTrabajador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreProceduresEF/Views/Trabajadores/TrabajadoresOficio.cshtml
@model TrabajadoresModel
@{
    List<string> oficiosList =
            ViewData["OFICIOS"] as List<string>;
}

<h1>Procedimiento salida Trabajadores</h1>

<a asp-controller="Trabajadores" asp-action="Index" 
class="btn btn-success">
    Volver
</a>

<form method="post">
    <label>Seleccione un oficio</label>
    <select name="oficio" class="form-control">
        @foreach(string of in oficiosList)
        {
            <option>@of</option>
        }
    </select>
    <br />
    <button class="btn btn-outline-info">Buscar</button>
</form>

@if(Model != null)
{
    <h2>Personas: @Model.Personas</h2>
    <h2>Media salarial: @Model.MediaSalarial</h2>
    <h2>Suma salarial @Model.SumaSalarial</h2>
    <br />
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Trabajador tr in Model.Trabajadores)
            {
                <tr>
                    <td>@tr.Apellido</td>
                    <td>@tr.Oficio</td>
                    <td>@tr.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}